[project]
name = "analytics-on-un-population"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "siva1501", email = "sivashankarreddysiva742@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
]

[project.scripts]
analytics-on-un-population = "analytics_on_un_population:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
